"""Programmatic audit of any DCF xlsx generated by build_dcf_xlsx.py.

Usage:
    python audit_xls.py --xlsx cases/inditex/dcf.xlsx
"""

import argparse
import re
from pathlib import Path

from openpyxl import load_workbook

ERROR_VALUES = {"#REF!", "#VALUE!", "#N/A", "#DIV/0!", "#NAME?", "#NULL!", "#NUM!"}


def audit(xlsx_path):
    xlsx_path = Path(xlsx_path)
    wb = load_workbook(xlsx_path, data_only=False)
    ws = wb.active
    issues = []
    info = []

    formula_count = 0
    hardcode_warnings = []
    cells_with_value = set()
    all_referenced = set()

    for row in ws.iter_rows():
        for cell in row:
            if cell.value is None:
                continue
            cells_with_value.add(cell.coordinate)
            if isinstance(cell.value, str) and cell.value.startswith("="):
                formula_count += 1
                for err in ERROR_VALUES:
                    if err in cell.value:
                        issues.append(f"ERROR string in formula at {cell.coordinate}: {cell.value}")
                refs = re.findall(r"\$?[A-Z]{1,3}\$?\d+", cell.value)
                for r in refs:
                    all_referenced.add(r.replace("$", ""))

    # Verify FCF formula structure (row 53)
    fcf_y1 = ws.cell(row=53, column=2).value
    fcf_ok = fcf_y1 and "+B47" in str(fcf_y1) and "-B51" in str(fcf_y1) and "-B52" in str(fcf_y1)
    info.append(f"{'PASS' if fcf_ok else 'CHECK'}: FCF Y1 formula structure ({fcf_y1})")

    # Verify discount factor uses absolute WACC ref
    pv_factor_y1 = ws.cell(row=55, column=2).value
    pv_ok = pv_factor_y1 and "$C$24" in str(pv_factor_y1)
    info.append(f"{'PASS' if pv_ok else 'CHECK'}: Discount factor absolute WACC ref ({pv_factor_y1})")

    # Verify WACC formula references cost of equity
    wacc_formula = ws.cell(row=24, column=3).value
    wacc_ok = wacc_formula and "C20" in str(wacc_formula)
    info.append(f"{'PASS' if wacc_ok else 'CHECK'}: WACC references cost of equity ({wacc_formula})")

    # Verify implied share price formula
    implied_price = ws.cell(row=72, column=3).value
    info.append(f"Implied share price formula: {implied_price}")

    # Sanity: terminal % of EV (row 75) — can't compute without recalc, just report formula
    tv_pct = ws.cell(row=75, column=3).value
    info.append(f"Terminal % of EV formula: {tv_pct}")

    print("=" * 80)
    print(f"DCF MODEL AUDIT REPORT - {xlsx_path.name}")
    print("=" * 80)
    print(f"\nISSUES ({len(issues)}):")
    if not issues:
        print("  None.")
    for i in issues:
        print(f"  - {i}")
    print(f"\nCHECKS:")
    for i in info:
        print(f"  {i}")
    print(f"\nSTATS:")
    print(f"  Total formulas: {formula_count}")
    print(f"  Total cells with values: {len(cells_with_value)}")
    print(f"  Dimensions: {ws.dimensions} ({ws.max_row} rows x {ws.max_column} cols)")
    print(f"\nRECOMMENDATION:")
    print(f"  Open xlsx in Excel/LibreOffice to force recalc and verify implied price matches compute_dcf.py output.")
    return len(issues) == 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--xlsx", required=True)
    args = parser.parse_args()
    ok = audit(args.xlsx)
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
