[theme]
primaryColor = "#1DB954"
backgroundColor = "#121212"
secondaryBackgroundColor = "#181818"
textColor = "#FFFFFF"
font = "sans-serif"
base = "dark"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
